baseurl = "http://betingelser.blankoslo.no"
languageCode = "no-nb"
title = "Betingelser i Blank"
GoogleAnalytics = "UA-66155927-6"

[params]
  intro_title = "Lønn og goder i Blank"
  intro_text = "Siden vi vet at det kan være vanskelig å orientere seg i markedet om hva som er konkurransedyktig lønn, vanlige goder eller andre prinsipper, har vi her lagt ut litt mer om våre betingelser og tankene bak. Vi håper det kan være til nytte."
